spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: http://127.0.0.1:9090
          predicates:
            - Before=2024-08-26T00:00:00Z
#        - id: weight_high
#          uri: http://127.0.0.1:9090
#          predicates:
#            - Weight=group1, 8
#        - id: weight_low
#          uri: https://weightlow.org
#          predicates:
#            - Weight=group1, 2
#        - id : wolfman
#          uri: http://127.0.0.1:9090
#          predicates:
#            - Wolfman=wolfman, wolfman
#        - id: after_route
#          uri: http://127.0.0.1:9090
#          predicates:
#            - After=2024-10-26T00:00:00Z
#        - id: add_request_header_route
#          predicates:
#            - Path=/customer/default-customer-name
#          filters:
#            - AddRequestHeader=X-Request-Red, Blue
#          uri: http://127.0.0.1:9090
        - id: add_request_headers_route_2
          uri: http://127.0.0.1:9090
          predicates:
            - Path=/customer/default-customer-name
          filters:
            - AddRequestHeadersIfNotPresent=X-Request-Color-1:blue,X-Request-Color-2:green

#logging:
#  level:
#    root: debug